---
title: <font color="#66C2A5">Descriptives</font>
csl: apa-custom-no-issue.csl
output: 
  html_document:
    code_folding: "hide"
editor_options: 
  chunk_output_type: console
---

## {.tabset}

### Library
```{r Library}
library(apaTables)
library(formr)
# library(effects)
# library(effectsize)
# library(lme4)
# library(sjstats)
# library(lmerTest)
library(ggplot2)
library(psych)
library(knitr)
library(dplyr)
library(jtools)
library(raincloudplots)

apatheme = theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        axis.line = element_line(),
        legend.title = element_blank(),
        plot.title = element_text(hjust = 0.5))

```

### Data
Load selected data based on 03_codebook
```{r}
data_included_documented = read.csv(file = "data_included_documented.csv")[,-1]

data_included_documented = data_included_documented %>%
  filter(!is.na(political_orientation))
```

### Missingness Pattern {.tabset}
```{r}
crosstabs(~ is.na(data_included_documented$pref_level_kind) +
            is.na(data_included_documented$pref_level_supportive))
```

### Summary {.tabset .active}
```{r Summary}
describe(data_included_documented %>%
           select_if(is.numeric)) %>%
  kable()
```

### Political Orientation {.tabset}
```{r Political Orientation}
mean(data_included_documented$political_orientation)
sd(data_included_documented$political_orientation)
range(data_included_documented$political_orientation)

# Daten in das richtige Format bringen
raincloud_data1 <- data_1x1(
  array_1 = data_included_documented$political_orientation,  array_2 = data_included_documented$political_orientation)
table(raincloud_data1$x_axis)

raincloud_data1$y_axis = raincloud_data1$y_axis + rnorm(n = 13257, mean = 0, sd = 0.02)

# Abbildung erstellen
raincloud <- raincloud_1x1(
  data = raincloud_data1, 
  colors = (c('forestgreen')), 
  fills = (c('forestgreen')), 
  size = 1, 
  alpha = .6, 
  ort = 'h') +

scale_x_continuous(breaks=c(0:6))  +
  #scale_y_continuous(breaks = c(0:6)) +
  ylab("Right-Wing Political Orientation") +
  #xlab("Right-Wing Political Orientation") +
  theme_bw() +
  theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.border=element_blank(),
        #axis.line.y = element_line(colour = "black"), 
        axis.line.x = element_line(colour = "black"), 
        axis.title.x =  element_text(size = 15),
        axis.text.x = element_text(size = 14, colour = "black"),
        axis.text.y = element_text(size = 14, colour = "black"),
        axis.ticks.y = element_blank())
raincloud

```

#### Save Image
```{r}
jpeg("Raincloud_PO.jpeg", width = 580, height = 436, res = 300)
raincloud
dev.off()
```

### Raincloud Plot Countries 
```{r}
# Create new dataset including only lines where country== France, Germany, USA, Mexico, Italy, Brazil, Spain
data_included_documented_raincloud_countries <- data_included_documented %>% filter(grepl('France|Germany|United States of America|Mexico|Italy|Brazil|Spain', country))

#Separate datasets for each country
data_France <- data_included_documented %>% 
  filter(grepl('France', country))
data_Germany <- data_included_documented %>% 
  filter(grepl('Germany', country)) 
data_USA <- data_included_documented %>% 
  filter(grepl('United States of America', country))
data_Mexico <- data_included_documented %>% 
  filter(grepl('Mexico', country))
data_Italy <- data_included_documented %>% 
  filter(grepl('Italy', country))
data_Brazil <- data_included_documented %>% 
  filter(grepl('Brazil', country))
data_Spain <- data_included_documented %>% 
  filter(grepl('Spain', country))

# Bring data in the right format
raincloud_data2 <- data_1x1(
  array_1 = data_France$political_orientation,  
  array_2 = data_Germany$political_orientation, 
  array_3 = data_USA$political_orientation,
  array_4 = data_Mexico$political_orientation,
  array_5 = data_Italy$political_orientation,
  array_6 = data_Brazil$political_orientation,
  array_7 = data_Spain$political_orientation,)
table(raincloud_data2$x_axis)

raincloud_data2$y_axis = raincloud_data2$y_axis + rnorm(n = 8606, mean = 0, sd = 0.02)

# Abbildung erstellen
raincloud2 <- raincloud_1x1(
  data = raincloud_data2, 
  colors = (c('forestgreen','blue')), 
  fills = (c('forestgreen','blue')), 
  size = 1, 
  alpha = .6, 
  ort = 'h') +

scale_x_continuous(breaks=c(1,2,3,4,5,6,7), labels=c("France", "Germany", "United States of America", "Mexico", "Italy", "Brazil", "Spain"), limits=c(0.5, 3)) +
  scale_y(breaks = c(0:6)) +
  ylab("Right-Wing Political Orientation") +
  xlab("") +
  theme_bw() +
  theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.border=element_blank(),
        axis.line.y = element_line(colour = "black"), 
        axis.line.x = element_line(colour = "black"), 
        axis.title.x =  element_text(size = 15),
        axis.text.x = element_text(size = 14, colour = "black"),
        axis.text.y = element_text(size = 14, colour = "black"),
        axis.ticks.y = element_blank())
raincloud2
```

### Correlations for Ideal Partner Preferences {.tabset}
```{r Correlations for ideal partner preferences}
cor.test(data_included_documented$pref_level_financially_secure,
         data_included_documented$pref_level_successful_ambitious,
         conf.level = 0.95)

cor.test(data_included_documented$pref_level_kind,
         data_included_documented$pref_level_supportive,
         conf.level = 0.95)

cor.test(data_included_documented$pref_level_attractive_body,
         data_included_documented$pref_level_attractive_face,
         conf.level = 0.95)


cor.test(data_included_documented$pref_level_confident,
         data_included_documented$pref_level_assertive,
         conf.level = 0.95)

cor.test(data_included_documented$pref_level_intelligence,
         data_included_documented$pref_level_educated,
         conf.level = 0.95)
```

### Language {.tabset}
```{r}
n = nrow(data_included_documented)

table(data_included_documented$language)

round((table(data_included_documented$language)/n)*100,2)
```

### Country {.tabset}
```{r}
country_absolute = as.data.frame(table(data_included_documented$country))

country_freq = as.data.frame(round((table(data_included_documented$country)/n)*100,2))

country = left_join(country_absolute, country_freq, by = "Var1")
country

write.table(country, file = "country.txt", sep = ",")
```

### Descriptives and Correlation Table {.tabset}
```{r}
cor = data_included_documented %>%
  select(political_orientation,
          age,
         interest_single,
         interest_sexrel, 
         interest_nonmonrel, 
         interest_monrel, 
         pref_politicalsim, 
         pref_ethnicalsim, 
         pref_religioussim,
          pref_level_financially_secure_successful_ambitious,
         pref_level_kind_supportive, 
         pref_level_attractiveness, 
         pref_level_confident_assertive,
         pref_level_intelligence_educated, 
         imp_age, 
         ideal_age, 
         imp_height, 
         ideal_height) 
         #ideal_age_rel)
round(cor(cor, use="pairwise.complete.obs"),2)
apa_table_cor = apa.cor.table(cor, filename = "descriptives.doc")
```
