---
title: <font color="#66C2A5">Descriptives</font>
csl: apa-custom-no-issue.csl
output: 
  html_document:
    code_folding: "hide"
editor_options: 
  chunk_output_type: console
---

## {.tabset}

### Library
```{r Library}
library(apaTables)
library(formr)
# library(effects)
# library(effectsize)
# library(lme4)
# library(sjstats)
# library(lmerTest)
library(ggplot2)
library(psych)
library(knitr)
library(dplyr)
library(jtools)

apatheme = theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        axis.line = element_line(),
        legend.title = element_blank(),
        plot.title = element_text(hjust = 0.5))

```

### Data
Load selected data based on 03_codebook
```{r}
data_included_documented = read.csv(file = "data_included_documented.csv")[,-1]

data_included_documented = data_included_documented %>%
  filter(!is.na(political_orientation))
```

### Missingness Pattern {.tabset}
```{r}
crosstabs(~ is.na(data_included_documented$pref_level_kind) +
            is.na(data_included_documented$pref_level_supportive))
```

### Summary {.tabset .active}
```{r Summary}
describe(data_included_documented %>%
           select_if(is.numeric)) %>%
  kable()
```

### Political Orientation {.tabset}
```{r Political Orientation}
mean(data_included_documented$political_orientation)
sd(data_included_documented$political_orientation)
range(data_included_documented$political_orientation)

hist <- ggplot(data_included_documented, aes(x = political_orientation)) + 
  geom_histogram(col = "grey", binwidth = 0.5, center = 0) +
  labs(x = "Political Orientation", y = "Number of Participants")+ 
  theme(text = element_text(size=15), axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10))+
 scale_x_continuous(breaks=c(0, 1, 2, 3, 4, 5, 6))+
  apatheme
```

#### Save Image
```{r}
jpeg("PO_Histogram.jpeg", width = 1580, height = 836, res = 300)
hist
dev.off()
```

### Correlations for Ideal Partner Preferences {.tabset}
```{r Correlations for ideal partner preferences}
cor.test(data_included_documented$pref_level_financially_secure,
         data_included_documented$pref_level_successful_ambitious,
         conf.level = 0.95)

cor.test(data_included_documented$pref_level_kind,
         data_included_documented$pref_level_supportive,
         conf.level = 0.95)

cor.test(data_included_documented$pref_level_attractive_body,
         data_included_documented$pref_level_attractive_face,
         conf.level = 0.95)


cor.test(data_included_documented$pref_level_confident,
         data_included_documented$pref_level_assertive,
         conf.level = 0.95)

cor.test(data_included_documented$pref_level_intelligence,
         data_included_documented$pref_level_educated,
         conf.level = 0.95)
```

### Language {.tabset}
```{r}
n = nrow(data_included_documented)

table(data_included_documented$language)

round((table(data_included_documented$language)/n)*100,2)
```

### Country {.tabset}
```{r}
country_absolute = as.data.frame(table(data_included_documented$country))

country_freq = as.data.frame(round((table(data_included_documented$country)/n)*100,2))

country = left_join(country_absolute, country_freq, by = "Var1")
country

write.table(country, file = "country.txt", sep = ",")
```

### Descriptives and Correlation Table {.tabset}
```{r}
cor = data_included_documented %>%
  select(political_orientation,
          age,
         interest_single,
         interest_sexrel, 
         interest_nonmonrel, 
         interest_monrel, 
         pref_politicalsim, 
         pref_ethnicalsim, 
         pref_religioussim,
          pref_level_financially_secure_successful_ambitious,
         pref_level_kind_supportive, 
         pref_level_attractiveness, 
         pref_level_confident_assertive,
         pref_level_intelligence_educated, 
         imp_age, 
         ideal_age, 
         imp_height, 
         ideal_height) 
round(cor(cor, use="pairwise.complete.obs"),2)
apa_table_cor = apa.cor.table(cor, filename = "descriptives.doc")
```
