---
title: "07_graphs"
author: "Lena Kuschel"
date: "17 November 2020"
output: 
  html_document:
    code_folding: "hide"
---

## Graphs {.tabset}

### Library
```{r Library}
library(formr)
library(effects)
library(effectsize)
library(lme4)
library(sjstats)
library(lmerTest)
library(ggplot2)
library(tidyr)
library(ggpubr)
library(RColorBrewer)
library(coefplot)
library(dplyr)


apatheme = theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        axis.line = element_line(),
        legend.title = element_blank(),
        plot.title = element_text(hjust = 0.5))
```


### Data
Load selected data based on 03_codebook
```{r}
data_included_documented = read.csv(file = "data_included_documented.csv")[,-1]
data_included_documented = data_included_documented %>%
  filter(!is.na(political_orientation)) #check
```

### Figure 2 {.tabset}
Effect size estimates of linear effects of political orientation on preferred relationship options for main analyses and one robustness analyses.

#### Main Analyses
```{r}
model_interest_single <-
  as.data.frame(
    standardize_parameters(
      lmer(
        interest_single ~ political_orientation + (1|country),
        data = data_included_documented),
      method = "basic", ci = 0.997))

model_interest_sexrel <-
  as.data.frame(
    standardize_parameters(
      lmer(
        interest_sexrel ~ political_orientation + (1+political_orientation|country),
        data = data_included_documented),
      method = "basic", ci = 0.997))

model_interest_nonmonrel <-
  as.data.frame(
    standardize_parameters(
      lmer(
        interest_nonmonrel ~ political_orientation + (1|country),
        data = data_included_documented),
      method = "basic", ci = 0.997))

model_interest_monrel <-
  as.data.frame(
    standardize_parameters(
      lmer(
        interest_monrel ~ political_orientation + (1+political_orientation|country),                              data = data_included_documented),
      method = "basic", ci = 0.997))
```

#### Robustness Analyses
Addtionally including age as a predictor
```{r}
model_interest_single_robustcheck <-
  as.data.frame(
    standardize_parameters(
      lmer(
        interest_single ~political_orientation + age + (1+political_orientation|country),
        data = data_included_documented),
      method = "basic", ci = 0.997))

model_interest_sexrel_robustcheck <-
  as.data.frame(
    standardize_parameters(
      lmer(
        interest_sexrel ~ political_orientation + age + (1+political_orientation|country),
        data = data_included_documented),
      method = "basic", ci = 0.997))

model_interest_nonmonrel_robustcheck <-
  as.data.frame(
    standardize_parameters(
      lmer(
        interest_nonmonrel ~ political_orientation + age + (1+political_orientation|country),
        data = data_included_documented),
      method = "basic", ci = 0.997))

model_interest_monrel_robustcheck  <-
  as.data.frame(
    standardize_parameters(
      lmer(
        interest_monrel ~ political_orientation + age + (1|country),
        data = data_included_documented),
      method = "basic", ci = 0.997))
```



#### Combine {.active}
```{r}
all_models_interest <- rbind(
  model_interest_single,
  model_interest_sexrel,
  model_interest_nonmonrel,
  model_interest_monrel,
  model_interest_single_robustcheck,
  model_interest_sexrel_robustcheck,
  model_interest_nonmonrel_robustcheck,
  model_interest_monrel_robustcheck) %>%
  filter(Parameter == "political_orientation")

all_models_interest$hypothesis = factor(
  rep(c("H1a) Single", "H1b) Sexual Relationship",
        "H1c) Nonmonogamous Relationship", "H1d) Monogamous Relationship"),
      2),
  levels = c("H1d) Monogamous Relationship", "H1c) Nonmonogamous Relationship",
             "H1b) Sexual Relationship", "H1a) Single"))

all_models_interest$type = factor(
  c(rep("Main Analyses", 4), rep("Robustness Analyses", 4)),
  levels = c("Robustness Analyses", "Main Analyses"))

multiplot = ggplot(all_models_interest, aes(hypothesis, Std_Coefficient)) +
  geom_pointrange(data = all_models_interest,
                  mapping = aes(x = hypothesis, y = Std_Coefficient,
                                ymin = CI_low, ymax = CI_high, group = type,
                                color = type),
                  position = position_dodge(width=0.3)) + 
  geom_hline(yintercept = 0, size = 1.5)  +
  geom_hline(yintercept = -.05, linetype = "dotted", size = 1.5) + 
  geom_hline(yintercept = .05, linetype = "dotted", size = 1.5) +
  coord_flip() +
  apatheme +
  scale_colour_manual(values = c("#86BDDB", "#084594"))  +
  labs(y = "Linear Effect of Political Orientation", x = "Outcome") +
  theme(text = element_text(size=15), axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        legend.text = element_text(size = 10),
        plot.title = element_text(hjust = 0),
        legend.background = element_rect(fill="grey", 
                                         size=0.5, linetype="solid"))
multiplot
```

#### Save image
```{r}
jpeg("Figure2.jpeg", width = 1050, height = 700, pointsize = 100, quality = 100)
multiplot
dev.off()
```


